<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PicoGK" Version="1.4.0" />
  </ItemGroup>

  <ItemGroup>
    <NativeReference Include="../Native/build/libuhtc_native_accel.so" />
  </ItemGroup>

</Project>
